[solana]
rpc = "https://api.mainnet-beta.solana.com"
websocket = "wss://api.mainnet-beta.solana.com"
program-id = "8X7bEsKtuLqRcEM7s7RJ9wiCwdbdQ56yZQapYX5vVfjV"
network-type = "local"

[rest]
port = 8080
