[solana]
# rpc = "http://localhost:8899"
rpc = "https://api.devnet.solana.com"
# websocket = "ws://localhost:8900"
websocket = "wss://api.devnet.solana.com"
program-id = "8zjg3UihgxJ3H8AtWfLdGkfBGauVyvJHAQaKW8v1y4Mj"
network-type = "local"

[rest]
port = 8085
